# Use the official Node.js image as the base image
FROM node:10.16.0

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the working directory
COPY package.json ./

# Install the application dependencies
RUN npm install

# Build the React application
RUN npm run build

# Bundle app source
COPY . /app

# Expose port 3000
EXPOSE 3000

# Define the entry point for the container
CMD ["npm", "start"]